### ISSUE TITLE
implementar atualização de arquivos após comrpa

### ISSUE THREAD

**Issue by armando-almeida** [armando-almeida/PBL2_TEC502#3]
Salvar os dados das passagens, como origem, trecho, quantidade de passagem e o servidor alocado num json

**Comment by Armaaaaaaaaaaaaaaaaaaaaaaaaaaando** [comment]
precisa terminar, ele já está salvando as cidades no json, mas precisa fazer com que os servidores leiam os dados desse json. 
alem de, atualizar o json, quando é feita uma compra.

**Comment by Armaaaaaaaaaaaaaaaaaaaaaaaaaaando** [comment]
está faltando atualizar os arquivos após uma compra ser feita
